### ISSUE TITLE
Connecting to frida-gadget? (frida.ProcessNotFoundError)

### ISSUE THREAD

**Issue by Manouchehri** [agustingianni/memrepl#1]
Having a bit of trouble getting memrepl to work against remote applications, any suggestions?

## Target/Remote Machine
```
root@s5:/# LD_PRELOAD=/apps/frida-gadget-10.6.10-linux-x86_64.so /bin/ls
```

## Debugger/Host Machine
```
dave@65b7fe7b9a12:/tools/memrepl# socat TCP-LISTEN:27042,bind=127.0.0.1,fork,reuseaddr TCP:172.17.0.3:27042 &
dave@65b7fe7b9a12:/tools/memrepl# memrepl -d tcp -l
Using device Device(id="tcp", name="Local TCP", type='remote').
Local processes list:
  PID    Name
  205    Gadget
dave@65b7fe7b9a12:/tools/memrepl# memrepl -d tcp -p 205
Using device Device(id="tcp", name="Local TCP", type='remote').
Attaching to process pid `205`.
Attaching to process `205`.
Traceback (most recent call last):
  File "/usr/local/bin/memrepl", line 9, in <module>
    load_entry_point('memrepl==1.0', 'console_scripts', 'memrepl')()
  File "build/bdist.linux-x86_64/egg/memrepl.py", line 498, in main
  File "build/bdist.linux-x86_64/egg/memrepl.py", line 281, in __init__
  File "build/bdist.linux-x86_64/egg/frida/__init__.py", line 57, in attach

  File "build/bdist.linux-x86_64/egg/frida/core.py", line 97, in attach
frida.ProcessNotFoundError: unable to find process with pid 205
dave@65b7fe7b9a12:/tools/memrepl# memrepl -d tcp -n Gadget
Using device Device(id="tcp", name="Local TCP", type='remote').
Defaulting to first process `Gadget:205`.
Attaching to process `205`.
Traceback (most recent call last):
  File "/usr/local/bin/memrepl", line 9, in <module>
    load_entry_point('memrepl==1.0', 'console_scripts', 'memrepl')()
  File "build/bdist.linux-x86_64/egg/memrepl.py", line 498, in main
  File "build/bdist.linux-x86_64/egg/memrepl.py", line 281, in __init__
  File "build/bdist.linux-x86_64/egg/frida/__init__.py", line 57, in attach

  File "build/bdist.linux-x86_64/egg/frida/core.py", line 97, in attach
frida.ProcessNotFoundError: unable to find process with pid 205
```

**Comment by agustingianni** [comment]
Hi there, I've never tested it with remote applications. I will give it a look. Thanks for the bug report.
